### PR TITLE
Fix titlebar dimming on Wayland

### LINKED ISSUE #115: Application loses focus while moving window on wayland
Try moving a Qt window on wayland. Notice how the window gets unfocused while moving it (the titlebar gets dimmed). This does not happen when running the application with `QT_QPA_PLATFORM=xcb`.

### PR DESCRIPTION
**Pull request by polter-rnd**
Use correct active state detection. Partially fixes #115

Signed-off-by: Pavel Artsishevsky <polter.rnd@gmail.com>

### CODE REVIEW

**Comment by polter-rnd** [comment]
However this is not a complete fix. Application still loses focus, but titlebar remains active.

File: src/decoration/qgnomeplatformdecoration.cpp [hunk 1]
```diff
@@ -781,10 +782,8 @@ void QGnomePlatformDecoration::processMouseRight(QWaylandInputDevice *inputDevic
     startResize(inputDevice, Qt::RightEdge, b);
 }
 
-void QGnomePlatformDecoration::renderButton(QPainter *painter, const QRectF &rect, Adwaita::ButtonType button, bool renderFrame, bool sunken)
+void QGnomePlatformDecoration::renderButton(QPainter *painter, const QRectF &rect, Adwaita::ButtonType button, bool renderFrame, bool sunken, bool active)
```
Comment (grulja) [inline src/decoration/qgnomeplatformdecoration.cpp:785]: Instead of passing additional argument here, can you simply get the active state the same way we do in paint() method?

Comment (polter-rnd) [reply src/decoration/qgnomeplatformdecoration.cpp:785]: I thought about it, but seems that to do it right we need to copy all that new stuff there
```
#ifdef DECORATION_SHADOWS_SUPPORT // Qt 6.2.0+ or patched QtWayland
    windowStates = waylandWindow()->windowStates();
#else
    windowStates = window()->windowStates();
#endif
```

Comment (grulja) [reply src/decoration/qgnomeplatformdecoration.cpp:785]: I'm fine with that. It's something we will get rid of eventually one day in the future once we are sure we can rely only on `waylandWindow()`.

Comment (polter-rnd) [reply src/decoration/qgnomeplatformdecoration.cpp:785]: Actually I'm not sure now that my fix is done the right way, however it partially fixes the issue.. Looks like the right place to fix is in `qt5-qtwayland -> QWaylandWindow::isActive()` but I don't know if we can apply the same workaround there - I bet it will not be accepted.

So do you think we need this partial workaround in QGnomePlatform?

Comment (grulja) [reply src/decoration/qgnomeplatformdecoration.cpp:785]: Hard to say. I don't run GNOME at this moment and I will need to find some time to look into this.

Comment (polter-rnd) [reply src/decoration/qgnomeplatformdecoration.cpp]: I fiddled around with this and finally figured it out. That dimming occurred after commit [e532733](https://invent.kde.org/qt/qt/qtwayland/-/commit/e532733f7f4406d6b656c12cd107736dacd570e7) qt5-qtwayland. Since that, `window->isActive()` means only keyboard focus, and they don't use XdgShell hint to detect active window anymore. I've read the [discussion](https://codereview.qt-project.org/c/qt/qtwayland/+/367306/9) in the original change, and now it's pretty clear:

> From a Qt POV only one window can have focus. From a wayland POV only one window can have focus. Lots of things (like DataDevice) react to when things get keyboard focus.
> In early QtWayland we used to use keyboard events for this.
> 
> XdgShell added support for the shell to say which window was activated. The rationale behind this is that if you have a popup on a window the popup has focus, but because GTK has CSD's they needed something new to say to still render the CSD as active. Hence an additional property.
> 
> We didn't have to do anything with it, so we ignored it.
> Arguably we should expose it for our CSD decorations to use, rather than them querying the activeWindow.

So the only correct way for CSD to determine active state is to use `waylandWindow->windowStates()` which exist just for that purpose.

I've updated the PR, now I'm pretty sure this is the correct solution.
